services:
  zenoh:
    image: eclipse/zenoh:latest
    ports:
      - "7447:7447"
      - "8000:8000"
    environment:
      - RUST_LOG=info

  pub:
    build: ./app
    command: ["python", "-u", "pub.py"]
    depends_on:
      - zenoh

  sub:
    build: ./app
    command: ["python", "-u", "sub.py"]
    depends_on:
      - zenoh

  rust_sub:
    build: ./rust_sub
    depends_on:
      - zenoh
    environment:
      - RUST_LOG=rust_sub=debug,zenoh=info
    volumes:
      - ./rust_sub/out:/app/out
